import type { Explanation, SequenceExample } from '../presentation/plan.js';
import { anchor, html as escape, type Report } from './report.js';
import { REPORT_CSS, REPORT_JS } from './assets.js';

export function sequenceSvg(sequence: SequenceExample): string {
  const width = 780; const spacing = 600 / (sequence.participants.length - 1);
  const x = new Map(sequence.participants.map((item, i) => [item.key, 90 + i * spacing]));
  const height = 98 + sequence.messages.length * 58;
  return `<svg class="sequence" role="img" aria-labelledby="sequence-title sequence-desc" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
<title id="sequence-title">${escape(sequence.title)}</title><desc id="sequence-desc">${escape(sequence.assumption.text)} The ordered text version follows this diagram.</desc>
<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#245e4b"/></marker></defs>
${sequence.participants.map((item) => `<rect x="${x.get(item.key)! - 77}" y="10" width="154" height="36" rx="7" fill="#eaf0e7"/><text x="${x.get(item.key)}" y="33" text-anchor="middle" font-size="12" fill="#202f2c">${escape(item.label)}</text><line x1="${x.get(item.key)}" x2="${x.get(item.key)}" y1="50" y2="${height - 15}" stroke="#c7d1c5" stroke-dasharray="4 5"/>`).join('')}
${sequence.messages.map((msg, index) => { const y = 90 + index * 58; return `<line x1="${x.get(msg.from)}" x2="${x.get(msg.to)}" y1="${y}" y2="${y}" stroke="#245e4b" stroke-width="1.5" ${msg.kind === 'return' ? 'stroke-dasharray="5 4"' : ''} marker-end="url(#arrow)"/><text x="${(x.get(msg.from)! + x.get(msg.to)!) / 2}" y="${y - 10}" text-anchor="middle" font-size="12" fill="#202f2c">${escape(msg.label)}</text>`; }).join('')}</svg>`;
}
export function renderHtml(report: Report): string {
  const { model, plan, concept, claims, flow, claimLabels, steps, unknowns, relations, concepts, evidence, evidenceMap, entries } = report;
  const { request, proposal } = model.data;
  const refs = (ids: string[]) => ids.map((id) => { const item = evidenceMap.get(id)!; return `<a href="#${anchor(id)}">${escape(item.path)}:${item.start_line}</a>`; }).join(' ');
  const claimRefs = (ids: string[]) => ids.map((id) => `<a href="#${anchor(id)}">${claimLabels.get(id)}</a>`).join(', ');
  const support = (item: Explanation) => `<span class="support">${report.evidenceFor(item).map((id, i) => `<a href="#${anchor(id)}" aria-label="Open source excerpt ${i + 1}">Source${i ? ` ${i + 1}` : ''}</a>`).join('')}${item.unknown_indices.map((index) => `<a href="#unknown-${index}">Scope note</a>`).join('')}</span>`;
  const paragraph = (item: Explanation) => `<p>${escape(item.text)} ${support(item)}</p>`;
  const stageHtml = plan.stages.map((stage, index) => `<article class="stage" id="stage-${stage.key}" data-stage="${stage.key}">
<div class="stage-title"><span class="number">${String(index + 1).padStart(2, '0')}</span><h3>${escape(stage.title)}</h3></div>
<p class="stage-summary">${escape(stage.summary.text)} ${support(stage.summary)}</p>
${stage.cautions.map((item) => `<p class="caution"><strong>Watch for:</strong> ${escape(item.text)} ${support(item)}</p>`).join('')}
<details><summary>Explain this stage</summary><div class="detail-body">${stage.notes.map(paragraph).join('')}
<details class="exact"><summary>Exact branches (${stage.step_ids.length})</summary>${stage.step_ids.map((id) => { const step = steps.get(id)!; return `<div class="branch" id="${anchor(id)}"><h4>${escape(step.title)}</h4><p class="support">Claims: ${claimRefs(step.claim_ids)}. ${refs(step.evidence_ids)}</p>${step.next.length ? `<ul>${step.next.map((edge) => `<li>${edge.condition === null ? 'Then' : escape(edge.condition)} → <a href="#${anchor(edge.step_id)}">${escape(steps.get(edge.step_id)!.title)}</a> <span class="support">${refs(edge.evidence_ids)}</span></li>`).join('')}</ul>` : '<p>This branch ends within the recorded flow.</p>'}</div>`; }).join('')}</details>
<p class="inventory-link">Claims for this stage: ${claimRefs(stage.claim_ids)}</p></div></details></article>`).join('');
  const sequence = plan.sequence;
  const labels = new Map(sequence?.participants.map((item) => [item.key, item.label]));
  const diagram = sequence ? `<figure class="diagram"><h3>${escape(sequence.title)}</h3><p class="assumption">${escape(sequence.assumption.text)} ${support(sequence.assumption)}</p>${sequenceSvg(sequence)}<figcaption class="muted">Possible sequence under the stated condition. Dashed arrows show returns.</figcaption><details><summary>Read the sequence as text</summary><table class="sequence-table"><thead><tr><th>Order</th><th>From</th><th>To</th><th>Action</th><th>Support</th></tr></thead><tbody>${sequence.messages.map((msg, i) => `<tr><td>${i + 1}</td><td>${escape(labels.get(msg.from)!)}</td><td>${escape(labels.get(msg.to)!)}</td><td>${escape(msg.label)}</td><td>${claimRefs(msg.claim_ids)}</td></tr>`).join('')}</tbody></table></details></figure>` : '';
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${escape(concept.title)} · Clearings</title><style>${REPORT_CSS}</style></head>
<body><a class="skip" href="#overview">Skip to the report</a><aside class="rail"><a class="brand" href="#overview"><span class="mark" aria-hidden="true"><i></i><i></i><i></i></span>clearings</a><p class="rail-label">Capability guide</p><nav aria-label="Report sections"><a class="current" href="#overview">Overview</a><a href="#flow">Follow the flow</a><a href="#cases">Explore a case</a><a href="#unknowns">Scope and unknowns</a><a href="#claims">Claim inventory</a><a href="#evidence">Source evidence</a><a href="#report-details">Report details</a></nav><div class="rail-footer">Read at your own depth.<br>Each explanation links<br>back to the source.</div></aside>
<main class="shell"><div class="topbar"><span>CODE GUIDE</span><span class="pill"><span class="dot" aria-hidden="true"></span>Needs review</span></div>
<section class="hero" id="overview"><span class="eyebrow">${model.data.transport === 'recorded-replay' ? 'Recorded example' : 'Proposed explanation'} · ${plan.stages.length} stages</span><h1>${escape(concept.title)}</h1><p class="lede">${escape(plan.introduction.text)} ${support(plan.introduction)}</p><div class="hero-links"><a href="#flow">Follow the flow ↓</a><a href="#cases">Find a specific case ↓</a></div><p class="scope-line">${request.data.scope.paths.length} selected files · ${request.coverage.evidence_records} source excerpts · Partial repository view · <a href="#report-details">Scope and review details</a></p></section>
<section class="section" id="flow"><div class="section-heading"><div><span class="eyebrow">01 / Understand the behavior</span><h2>Follow the flow</h2><p>Start with the stages. Open one when you need more detail.</p></div></div><nav class="step-map" aria-label="Reading stages">${plan.stages.map((stage, index) => `<a href="#stage-${stage.key}" data-stage="${stage.key}"><span>${String(index + 1).padStart(2, '0')}</span>${escape(stage.title)}</a>`).join('')}</nav><p class="muted">These stages group related behavior. The conditions in each stage determine the path.</p>${diagram}${stageHtml}</section>
<section class="section" id="cases"><div class="section-heading"><div><span class="eyebrow">02 / Answer your question</span><h2>Explore a case</h2><p>Open a question to see the answer and its related stages.</p></div></div><div class="case-list">${plan.cases.length ? plan.cases.map((item) => `<details class="case" id="case-${item.key}" data-stages="${item.stage_keys.join(' ')}"><summary>${escape(item.question)}</summary><div class="detail-body">${item.answer.map(paragraph).join('')}<div class="case-links" aria-label="Related stages">${item.stage_keys.map((key) => `<a href="#stage-${key}">${escape(plan.stages.find((stage) => stage.key === key)!.title)} ↗</a>`).join('')}</div></div></details>`).join('') : '<p class="muted">No case explanations were supplied. Use the exact branches above.</p>'}</div></section>
<section class="section" id="unknowns"><span class="eyebrow">03 / Know the limits</span><h2>Scope and unknowns</h2><p class="muted">These limits remain part of the explanation. Source citations do not prove claim support.</p><ul class="unknown-list">${unknowns.map((item) => `<li id="unknown-${item.index}">${item.critical ? '<span class="unknown-label">CRITICAL</span>' : ''}${escape(item.question)} <span class="support">${refs(item.evidence_ids)}</span></li>`).join('')}</ul>${unknowns.length ? '' : '<p>No unknowns were supplied. This does not establish complete coverage.</p>'}</section>
<section class="section" id="claims"><span class="eyebrow">04 / Inspect the reasoning</span><h2>Claim inventory</h2><p class="muted">${claims.length} claims describe this capability. Their original text is preserved for review.</p><details class="audit"><summary>Open all ${claims.length} claims</summary>${claims.map((claim) => `<article class="claim" id="${anchor(claim.id)}"><div class="claim-title">${claimLabels.get(claim.id)} · ${escape(claim.category)} · unreviewed</div><p>${escape(claim.text)}</p><span class="support">${refs(claim.evidence_ids)}</span></article>`).join('')}</details></section>
<section class="section" id="evidence"><div class="section-heading"><div><span class="eyebrow">05 / Read the source</span><h2>Source evidence</h2><p>Exact excerpts from the recorded request.</p></div><button id="expand-evidence" class="small-button" data-enhance hidden>Open all excerpts</button></div>${evidence.map((item) => `<details class="source" id="${anchor(item.id)}"><summary>${escape(item.path)}:${item.start_line}–${item.end_line}</summary><div class="detail-body"><p class="source-meta">Evidence: ${escape(item.id)}<br>Blob: ${escape(item.blob_sha)}<br>UTF-8 bytes [${item.start_byte}, ${item.end_byte}). Columns ${item.start_column}–${item.end_column}.</p><pre><code>${escape(item.text)}</code></pre></div></details>`).join('')}</section>
<section class="section" id="report-details"><h2>Report details</h2><details class="metadata"><summary>Source, coverage, and record details</summary><dl><dt>Transport</dt><dd>${model.data.transport}</dd><dt>Producer</dt><dd>${escape(proposal.producer.name)}; model: ${escape(proposal.producer.model ?? 'not recorded')}</dd><dt>Origin</dt><dd>${proposal.producer.kind === 'agent' ? 'Model inference' : 'Human declaration'}. Claim support: unreviewed. Acceptance: proposed.</dd><dt>Presentation</dt><dd>${plan.origin}; ${plan.review_status}. Reference validation does not establish English entailment.</dd><dt>Semantic artifact</dt><dd><code>${model.artifact_id}</code></dd><dt>Snapshot</dt><dd><code>${model.snapshot_id}</code></dd><dt>Structural scan</dt><dd><code>${request.data.scan_artifact_id}</code></dd><dt>Selected paths</dt><dd>${request.data.scope.paths.map(escape).join('<br>')}</dd><dt>Evidence scope</dt><dd>${request.coverage.evidence_records} excerpts supplied; ${request.coverage.omitted_scope_evidence} other structural evidence records omitted.</dd><dt>Source scan</dt><dd>${request.data.scan_coverage.parsed_source_files}/${request.data.scan_coverage.selected_source_files} selected files parsed; ${request.data.scan_coverage.failed_source_files} failed; ${request.data.scan_coverage.support_source_files} support files.</dd><dt>Entry points</dt><dd>${entries.map((item) => `${escape(item.name)} in ${escape(item.path)}`).join('<br>')}</dd><dt>Flow entries</dt><dd>${flow.entry_step_ids.map((id) => `<a href="#${anchor(id)}">${escape(steps.get(id)!.title)}</a>`).join(', ')}</dd></dl><h4>Related state and components</h4><ul>${relations.map((item) => `<li>${escape(concepts.get(item.from_id)!.title)} — ${item.kind} → ${escape(concepts.get(item.to_id)!.title)} <span class="support">${refs(item.evidence_ids)}</span></li>`).join('')}</ul><h4>Source diagnostics</h4>${model.diagnostics.length ? `<ul>${model.diagnostics.map((item) => `<li>${escape(item.code)}: ${escape(item.message)}</li>`).join('')}</ul>` : '<p>No source errors or warnings were recorded.</p>'}</details></section>
<footer class="footer"><span>Clearings · Evidence remains one step away.</span><a href="#overview">Back to overview ↑</a></footer></main><script>${REPORT_JS}</script></body></html>\n`;
}
