class NativeEngine:
    def __init__(self, limits: str) -> None: ...
    def submit(self, plan: str, now: float) -> int: ...
    def advance(self, events: str, now: float, budget: int) -> str: ...
    def close(self) -> None: ...
    def snapshot(self) -> str: ...
