import { html as h, markdown as md, codeFence } from '../renderers/report.js';
import { REPORT_CSS } from '../renderers/assets.js';
import { assembleContext, type OperationContext } from './context.js';
import { checkOperation } from './check.js';
import { ClearingsError } from '../model/types.js';
import { formatExpression } from './expressions.js';
import type { OperationCheck, OperationObservation, SemanticSpecification, ValueType } from './model.js';

export interface CheckedScenario { name: string; operation_id: string; observation: OperationObservation; result: OperationCheck }
export interface SpecificationReportOptions { format?: 'html' | 'markdown'; maxBytes?: number; scenarios?: CheckedScenario[] }
const fence = (value: unknown) => codeFence(JSON.stringify(value, null, 2)).replace('typescript\n', 'json\n');
const typeName = (type: ValueType): string => type.kind === 'enum' ? type.values.join(' | ') : type.kind === 'list' ? `list of ${typeName(type.element)}` : type.kind === 'record' ? `{ ${Object.entries(type.fields).map(([name, field]) => `${name}: ${typeName(field)}`).join(', ')} }` : type.kind;
const anchor = (id: string) => 'record-' + Buffer.from(id).toString('hex');

export function renderOperationContext(context: OperationContext, options: SpecificationReportOptions = {}): string {
  if (options.format !== undefined && !['html', 'markdown'].includes(options.format)) throw new ClearingsError('INVALID_ARGUMENTS', 'Specification reports support html and markdown.');
  const root = context.operations[0]!;
  const scenarios = options.scenarios ?? [];
  for (const scenario of scenarios) if (scenario.result.artifact_id !== context.artifact_id || scenario.result.operation_id !== scenario.operation_id || !context.operations.some(operation => operation.id === scenario.operation_id)) throw new ClearingsError('INVALID_SELECTION', 'Report scenarios must belong to included operations in this specification.');
  const status = `${context.perspective === 'intended' ? 'Proposed intended behavior' : 'Proposed source interpretation'}. ${context.operations.length} operations. Source hashes checked; source authenticity and claim support are not established.`;
  if (options.format !== 'html') {
    return [`# ${md(root.name)}`, '', md(root.purpose), '', status, '', `Specification: \`${context.artifact_id}\`.`, '',
      '## A concrete case', '', ...(scenarios.length ? scenarios.flatMap(scenario => [`### ${md(scenario.name)}`, '', `Operation: \`${scenario.operation_id}\`. Scenario check: **${scenario.result.verdict}**.`, '', '<details>', '<summary>Open inputs, outcome, and checks</summary>', '', fence({ observation: scenario.observation, result: scenario.result }), '', '</details>', '']) : ['Inspect the conditions below to find the outcome for your case.', '']),
      ...(context.states.length ? ['## State used by these rules', '', '| State | Type | Meaning |', '| --- | --- | --- |', ...context.states.map(state => `| ${md(state.name)} | ${md(typeName(state.type))} | ${md(state.description)} |`), ''] : []),
      ...context.operations.flatMap(operation => [`<a id="${anchor(operation.id)}"></a>`, `## ${md(operation.name)}`, '', md(operation.purpose), '',
        '| Condition | Outcome | Required result |', '| --- | --- | --- |', ...operation.outcomes.map(outcome => `| ${md(formatExpression(outcome.when))} | ${md(outcome.description)} | ${md(outcome.ensures.map(rule => rule.description).join(' '))} |`), '',
        ...operation.guarantees.map(rule => `- ${md(rule.description)}`), '',
        ...(operation.implementations.length ? ['| Implementation | Responsibility |', '| --- | --- |', ...operation.implementations.map(item => `| ${md(item.name)} | ${md(item.responsibility)} |`), ''] : []),
        ...operation.decisions.map(item => `- **${item.disposition}${item.blocking ? '; blocking' : ''}:** ${md(item.question)} ${md(item.consequence)}`), '',
        '<details>', '<summary>Types, state, effects, and exact rules</summary>', '', fence(operation), '', '</details>', '']),
      '## Relationships', '', 'These are declared dependencies. The labels state their purpose; they are not an execution trace.', '', '| From | Target | Relationship | Role |', '| --- | --- | --- | --- |',
      ...context.links.map(link => `| ${md(context.operations.find(operation => operation.id === link.from_id)!.name)} | ${md(link.target_name ?? link.to_id)} | ${md(link.kind)} | ${md(link.role)}${link.included ? '' : ' (deferred)'} |`), '',
      '## Source and design evidence', '', ...context.sources.flatMap(source => [`<a id="${anchor(source.id)}"></a>`, '<details>', `<summary>${md(source.locator)}</summary>`, '', `Origin: ${source.origin}. SHA-256: \`${source.sha256}\`.`, '', codeFence(source.text).replace('typescript\n', source.origin === 'source' ? 'typescript\n' : 'text\n'), '', '</details>', '']),
      '## Context scope', '', `${context.budget.used_bytes} UTF-8 bytes in the canonical JSON package. Text rendering has a different size.`, '', fence(context.omissions), '', md(context.retrieval), '', 'Scenario checks evaluate supplied observations. They do not prove the implementation or authenticate requirements.', ''].join('\n');
  }
  const evidenceLinks = (ids: string[]) => ids.map(id => `<a href="#${anchor(id)}">Source</a>`).join(' · ');
  const checkView = (scenario: CheckedScenario) => `<details class="scenario"><summary>${h(scenario.name)} <span class="tag">${h(scenario.result.verdict)}</span></summary><p>Operation: ${h(scenario.operation_id)}. This checks supplied observations against the model.</p><pre tabindex="0" aria-label="Scenario inputs and outcome"><code>${h(JSON.stringify(scenario.observation, null, 2))}</code></pre><ul>${scenario.result.checks.map(check => `<li><strong>${h(check.verdict)}</strong> — ${h(check.description)}${check.reason ? ` ${h(check.reason)}` : ''}</li>`).join('')}</ul><p>${h(scenario.result.limitations.join(' '))}</p></details>`;
  return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(root.name)} · Clearings</title><style>${REPORT_CSS}
main{max-width:940px;margin:auto;padding:36px 24px}h1{max-width:24ch}section{margin:36px 0}.lead{font-size:1.18rem;max-width:70ch}.status{color:var(--muted);font-size:.9rem}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;margin:16px 0}th,td{padding:12px;text-align:left;vertical-align:top;border-bottom:1px solid var(--line)}td{min-width:120px}pre{padding:16px;overflow:auto;background:var(--soft);border-radius:8px}code{white-space:pre}details{margin:12px 0;padding:12px;border:1px solid var(--line);border-radius:8px}summary{cursor:pointer}p,td,li{overflow-wrap:anywhere}.tag{font-size:.85rem;margin-left:8px;color:var(--muted)}.rule{margin:12px 0}nav{display:flex;flex-wrap:wrap;gap:16px;margin:24px 0}@media(max-width:600px){main{padding:20px 14px}h1{font-size:2rem}th,td{padding:8px}}
</style></head><body><a class="skip" href="#main">Skip to content</a><main id="main"><p>Clearings · Internal representation for AI coding</p><h1>${h(root.name)}</h1><p class="lead">${h(root.purpose)}</p><p class="status">${h(status)}</p><nav aria-label="Reading path"><a href="#cases">Try a case</a><a href="#rules">Rules and outcomes</a><a href="#relationships">Relationships</a><a href="#evidence">Evidence</a></nav>
<section id="cases"><h2>A concrete case</h2>${scenarios.length ? scenarios.map(checkView).join('') : '<p>Start with an outcome condition below. Open its exact rule when you need the formal expression.</p>'}</section>
${context.states.length ? `<section id="state"><h2>State used by these rules</h2><div class="table-wrap" tabindex="0" aria-label="State definitions"><table><thead><tr><th>State</th><th>Type</th><th>Meaning</th></tr></thead><tbody>${context.states.map(state => `<tr><td>${h(state.name)}</td><td>${h(typeName(state.type))}</td><td>${h(state.description)} ${evidenceLinks(state.evidence_ids)}</td></tr>`).join('')}</tbody></table></div></section>` : ''}
<section id="rules"><h2>Rules and outcomes</h2>${context.operations.map(operation => `<article id="${anchor(operation.id)}"><h3>${h(operation.name)}</h3><p>${h(operation.purpose)}</p><div class="table-wrap" tabindex="0" aria-label="Conditional outcomes"><table><thead><tr><th>Condition</th><th>Outcome</th></tr></thead><tbody>${operation.outcomes.map(outcome => `<tr><td><code>${h(formatExpression(outcome.when))}</code></td><td>${h(outcome.description)} ${evidenceLinks(outcome.evidence_ids)}<details><summary>Required result and effects</summary><ul>${outcome.ensures.map(rule => `<li>${h(rule.description)}<br><code>${h(formatExpression(rule.predicate))}</code> ${evidenceLinks(rule.evidence_ids)}</li>`).join('')}${outcome.updates.map(update => `<li>Set ${h(update.state_id)} to <code>${h(formatExpression(update.value))}</code>.</li>`).join('')}${outcome.effects.map(effect => `<li>${h(effect.occurrence)} effect: ${h(effect.effect_id)}.</li>`).join('')}${outcome.transitions.map(transition => `<li>${h(transition.handoff)} ${h(transition.operation_id)}: ${h(transition.description)}</li>`).join('')}</ul></details></td></tr>`).join('')}</tbody></table></div>
${operation.guarantees.length ? `<ul>${operation.guarantees.map(rule => `<li>${h(rule.description)} ${evidenceLinks(rule.evidence_ids)}</li>`).join('')}</ul>` : ''}
${operation.implementations.length ? `<h4>Which implementation contributes?</h4><div class="table-wrap" tabindex="0" aria-label="Implementation responsibilities"><table><thead><tr><th>Implementation</th><th>Responsibility</th></tr></thead><tbody>${operation.implementations.map(item => `<tr><td>${h(item.name)}</td><td>${h(item.responsibility)} ${evidenceLinks(item.evidence_ids)}</td></tr>`).join('')}</tbody></table></div>` : ''}
${operation.decisions.length ? `<h4>Open boundaries</h4><ul>${operation.decisions.map(item => `<li><strong>${h(item.question)}</strong> ${h(item.consequence)} <span class="tag">${h(item.disposition)}${item.blocking ? '; blocking' : ''}</span></li>`).join('')}</ul>` : ''}
<details><summary>Types, state, and canonical operation</summary><p>Inputs: ${h(Object.entries(operation.inputs).map(([name, type]) => `${name}: ${typeName(type)}`).join('; ') || 'none')}.</p><p>Output: ${h(typeName(operation.output))}. State frame: ${h(operation.frame)}. Effect boundary: ${h(operation.effects.completeness)}.</p><pre tabindex="0" aria-label="Canonical operation JSON"><code>${h(JSON.stringify(operation, null, 2))}</code></pre></details></article>`).join('')}</section>
<section id="relationships"><h2>Relationships</h2><p>These are declared dependencies. Their roles do not establish an observed execution order.</p><div class="table-wrap" tabindex="0" aria-label="Operation relationships"><table><thead><tr><th>From</th><th>Target</th><th>Role</th></tr></thead><tbody>${context.links.map(link => `<tr><td>${h(context.operations.find(operation => operation.id === link.from_id)!.name)}</td><td>${link.included ? `<a href="#${anchor(link.to_id)}">${h(link.target_name!)}</a>` : h(link.target_name ?? link.to_id)}<br><span class="tag">${h(link.kind)}${link.included ? '' : '; deferred'}</span></td><td>${h(link.role)}</td></tr>`).join('')}</tbody></table></div></section>
<section id="evidence"><h2>Source and design evidence</h2><p>Attached text is exact. A valid hash establishes content integrity. Source authenticity, claim support, and requirement acceptance need separate checks.</p>${context.sources.map(source => `<details id="${anchor(source.id)}"><summary>${h(source.locator)}</summary><p>${h(source.origin)} · ${h(source.sha256)}</p>${source.binding ? `<p>Source artifact: ${h(source.binding.artifact_id)}. Snapshot: ${h(source.binding.snapshot_id ?? 'not supplied')}.</p>` : ''}<pre tabindex="0" aria-label="Exact attached source"><code>${h(source.text)}</code></pre></details>`).join('')}</section>
<details><summary>Package identity and omissions</summary><p>${h(context.artifact_id)}</p><p>${context.budget.used_bytes} UTF-8 bytes in the canonical JSON package. HTML has a different size.</p><pre tabindex="0" aria-label="Context omissions"><code>${h(JSON.stringify(context.omissions, null, 2))}</code></pre><p>${h(context.retrieval)}</p></details><p class="status">Scenario checks evaluate supplied observations. They do not prove the implementation or authenticate requirements.</p></main></body></html>\n`;
}
export function renderSpecification(spec: SemanticSpecification, selection: string, options: SpecificationReportOptions = {}): string {
  const context = assembleContext(spec, selection, { maxBytes: options.maxBytes ?? 2097152 });
  const scenarios = options.scenarios?.map(scenario => ({ ...scenario, result: checkOperation(spec, scenario.operation_id, scenario.observation) }));
  return renderOperationContext(context, { ...options, ...(scenarios ? { scenarios } : {}) });
}
